### ISSUE TITLE
can please update the prebuilt binary url? its not working

### ISSUE THREAD

**Issue by muja555** [flankerhqd/JAADAS#1]

**Comment by muja555** [comment]
and gradle fatJar ended with
[ant:javac] 100 errors
[ant:javac] 3 warnings
using gradle 2.13

**Comment by anantshri** [comment]
just to add to this same status irrespective of if you use openjdk or oracle jdk.

100 errors and 3 warnings 

Looks like we are missing some steps here.

On further checks looks like error is due to heros `gradle jar` inside hero's directory also gives simmilar results.

**Comment by flankerhqd** [comment]
Can you post some snippet of error logs? Thanks
OK, seems some library jars are filtered out during upload, working on that.

**Comment by anantshri** [comment]
attached with this
[heros_errorlog.txt](https://github.com/flankerhqd/JAADAS/files/298609/heros_errorlog.txt)

**Comment by anantshri** [comment]
I suppose that could be the reason of your .gitignore. also while you are at it. see if you can also do #2

**Comment by flankerhqd** [comment]
Can you verify the new commit fixes this issue?

**Comment by anantshri** [comment]
Let me check and confirm that.

**Comment by flankerhqd** [comment]
Also prebuilt binary link updated.

**Comment by anantshri** [comment]
Looks like i can compile however there are still multiple warning and besides that the file is created at jade/build/libs looks like rename has not been affected at all places. 

your document suggests "JAADAS is organized by gradle. Run gradle fatJar at the root of source directory and single-bundled jar will be generated at ./JAADAS/build/"

**Comment by flankerhqd** [comment]
Yes I do a find-replace on the readme.md to avoid potential trademark issue, as JADE is some trademark   used by some company. Will change README for that. Thanks.
The warnings are introduced by upstream heros and mostly template warnings which I don't think worth fixing.
