### ISSUE TITLE
您在wiki中介绍说Reachability Analysis还没有实现，不太懂是哪个部分还没有实现。

### ISSUE THREAD

**Issue by Watermelon12345** [flankerhqd/JAADAS#12]
您好，我刚刚接触静态分析不久，我看了您的分析看了很多遍，优化flowdroid这部分从修改污染传播规则到自定义添加漏洞插件，在Reachability Analysis时最后说，还没有实现，不太清楚您是具体哪部分没有实现，是您在前面介绍的从读取文件到扫描是否有权限泄露的函数，这部分没有实现吗？我没有理解清楚，期待您的回复。
另外，从优化JAADAS的角度看，您能提供一些思路吗？我想尝试着去分析理解然后优化它。

**Comment by flankerhqd** [comment]
这里指的是权限泄漏检测这部分，没有做给出如何到达权限泄漏代码的功能，wiki里表述不是很清楚。已经修改。
