### ISSUE TITLE
请问在output结果中输出的score是什么含义呢？给出的分数是如何判定的呢？

### ISSUE THREAD

**Issue by Watermelon12345** [flankerhqd/JAADAS#13]
{
  **"score": **133.39999389648438,****
  "md5hash": "1980980716b38a8ea7c28e652b82aedc",
  "results": [{
    "desc": "webview addjsinterface code exec",
    "sourceStmt": "virtualinvoke $r22.<com.energysource.szj.embeded.AdvWebView: void addJavascriptInterface(java.lang.Object,java.lang.String)>($r26, \"es\")",
    "custom": "naive check, may false positive",
    "vulnKind": 0,
    "destMethod": "",
    "paths": [],
    "destStmt": "",
    "sourceMethod": "<com.energysource.szj.embeded.AdManager: void requestAdvById(int)>"
  },

**Comment by flankerhqd** [comment]
https://github.com/flankerhqd/JAADAS/tree/master/jade/src/main/scala/org/k33nteam/jade/propagation/methodplugins

https://github.com/flankerhqd/JAADAS/blob/e37c9b4bdba2b8aada82820bb4cf3d7b0cc3dfb9/jade/src/main/scala/org/k33nteam/jade/bean/VulnResult.scala
里面有一些拍脑袋的score，每个类型的漏洞有一个分值

**Comment by Watermelon12345** [comment]
你好。我看了你给的第一个链接，里面有很多你自己写的插件，但是我对scala语言不是很熟悉，能不能简单介绍一下除了fakeId之外的其他插件是干什么用的呢，麻烦了(●￣(ｴ)￣●)。
