### ISSUE TITLE
Looking for config files in current / working directory.

### ISSUE THREAD

**Issue by anantshri** [flankerhqd/JAADAS#5]
The application on execution looks for config files in current / working directory. also zip provides them in folder called config but it appears they are searched for in working directory only.

Is it possible to fix the location of config files.

P.S. not an expert on scala and hence need a helping hand. 
This seems to be the only blocker in getting it Integrated in AndroidTamer

**Comment by flankerhqd** [comment]
I think the -c option allows the jar to specify config directory, as the document states. have you tried this?

**Comment by anantshri** [comment]
Looks like -c might have some problems.

```
android@tamer /v/testing> /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Xmx512m -jar /usr/share/jaadas/jade.jar -c /usr/share/jaadas/config  -f /vagrant/testing/diva-beta.apk -p /opt/Arsenal/android-sdk-linux/platforms
Error: Unknown option -c
Error: Unknown argument '/usr/share/jaadas/config'
Joint Application Defect asseEsment - JADA 1.0alpha, author flanker
Usage: jade [vulnanalysis|fuzzgen] [options]

  -f <value> | --apkFile <value>
        specify the target apkpath
  -p <value> | --androidlib <value>
        specify the android platform path: e.g. /home/xxx/adt-bundles/sdk/platforms
Command: vulnanalysis [options]
do static vulnanalysis
  --fastanalysis
        use --fastanalysis to do only fast checks, i.e. API vulnerabilities and Crash Analysis
  --enableFlowOut
        use --enableFlowOut to do password flowout check, but note this maybe slow and too much memory consumption
  --redis <value>
        store json result in redis
  -c <value> | --configDirPath <value>
        specify config dir path, should contains the following files: ConstantRules.groovy AndroidCallbacks.txt SourcesAndSinks.txt direct.txt
Command: fuzzgen
generate fuzz commands
Oops, bad args! Memeda doesn't like slipper
android@tamer /v/testing>
```

**Comment by anantshri** [comment]
Also it would be wonderful if you can enable an option to specify custom write location -o  for example.

current write in current directory might not be the best way out.

**Comment by flankerhqd** [comment]
You're missing the 'vulnanalysis' string, which is option mode. Should be 

/usr/lib/jvm/java-8-openjdk-amd64/bin/java -Xmx512m -jar /usr/share/jaadas/jade.jar vulnanalysis -c /usr/share/jaadas/config/  -f /vagrant/testing/diva-beta.apk -p /opt/Arsenal/android-sdk-linux/platforms

Also currently its not happy with `config`, but `config/`, I will work around that.

**Comment by anantshri** [comment]
Thanks a lot for the quick work on this. I think package looks all good. should be available in Android Tamer in next few hours.
