### ISSUE TITLE
name change: jaadas

### ISSUE THREAD

**Issue by anantshri** [flankerhqd/JAADAS#6]
the binary jar is still named as jade as well as the folder where binary is created is still named as jade. Is this what's expected or are we changing these to jaadas in near future.

**Comment by flankerhqd** [comment]
Well I don't think it will be changed. Anyway filenames should be safe from trademark issues :)

**Comment by anantshri** [comment]
awesome just needed a confirmation before i push out package otherwise people might had to download package again. expect an annoucemnt over twitter for package availability.

**Comment by flankerhqd** [comment]
Thanks :)
