### ISSUE TITLE
How to use this tool

### ISSUE THREAD

**Issue by pentagramz** [flankerhqd/JAADAS#7]
Could you pls help

**Comment by flankerhqd** [comment]
Hello:

You can download the prebuilt binary at https://github.com/flankerhqd/JAADAS/releases/download/release0.1/jaadas-0.1.zip 

And then extract it.

For example you extract it to `/home/test/JAADAS/`, and you want to find vulnerabilities in APK whose filename is `sample.apk`. Your android SDK location is `/home/test/android-sdks/`,  then you can do a quick analysis using 

`java -jar jade-0.1.jar vulnanalysis -f sample.apk -p /home/test/android-sdks/platforms/ -c /hometest/JAADAS/config/ --fastanalysis`

If soot complains about `missing corresponding android sdk library`, for example, the APK you want to analysis has a target SDK of `android-21`, then you will need to use `sdk-manager` of android to download the SDK for `android-21`, or you can simply make a symlink to comfort Soot.

If you want to do full but slower analysis, use

`java -jar jade-0.1.jar vulnanalysis -f sample.apk -p /home/test/android-sdks/platforms/ -c /hometest/JAADAS/config/`

Both will have their results printed in JSON format, with description, vulnerable method locations and statements in each JSON representation,

**Comment by pentagramz** [comment]
![jaadas](https://cloud.githubusercontent.com/assets/7072014/22685581/df18434e-ed46-11e6-9a0e-a65fe892e751.PNG)
Is the tool runnning fine?

**Comment by flankerhqd** [comment]
Hello:

You need to adjust your absolute path. Your path is not /home/test. I don't known the full path on your machine, if it's /home/android/D/T/JAADAS, you need to replace /home/test with that.

**Comment by pentagramz** [comment]
Thanks a lot..the tool is working fine finally

**Comment by flankerhqd** [comment]
Good to hear that!

**Comment by pentagramz** [comment]
For certain apps the tool doesnt work

**Comment by pentagramz** [comment]
![jaadas](https://cloud.githubusercontent.com/assets/7072014/22782106/8ff1479c-eeeb-11e6-91f0-7670319b4ec4.PNG)

**Comment by pentagramz** [comment]
Does this require huge RAM?????

**Comment by flankerhqd** [comment]
Hi:

Your android-sdk is missing android-16 sdk platform jars, you can either install it using android sdk manager, or just make a symbol link from android-16 to your existing android platform jars, as specified in the main page of this project.

This tool may requires 4GB ram or more. If you are really short on RAM, try `fastanalysis` to get a quicker and lightweighted result.

**Comment by flankerhqd** [comment]
Installing android-23 sdk platform jars is also an option, as the APK you're trying to analysis has a targetSDKversion of android-23.

**Comment by mapmap95** [comment]
I have apk of android app.
How can I use jaadas tool for security testing?
Can you help me,please?
